import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:flutter/material.dart';
import 'dart:async';

import 'MenuModel.dart';

class MenuApi {
  MenuApi({required this.id, required this.token});
  String id, token;
  static Future<Result3?> getMenus(id, token) async {
    final response = await http.post(
        Uri.parse(
            'https://hello-cycu-delivery-service.herokuapp.com/member/store/detail'),
        headers: {
          "token": token,
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: {
          "id": id,
        });

    if (response.statusCode == 200) {
      print('status in form4${response.statusCode}');

      print('${response.body}');
      var obj = Autogenerated.fromJson(jsonDecode(response.body));
      var myaddress = (obj.result as Result3?);
      return myaddress;
    } else if (response.statusCode == 403) {
      print('status in form4 ${response.statusCode}');
      return null;
    } else {
      debugPrint('Failed to load store');
      throw Exception('Failed to load store');
    }
  }
}
