import 'package:flutter/widgets.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:async';

import 'groupModel.dart';

class groupApi {
  groupApi({required this.token});
  String token;
  static Future<List<Result2?>?>? getGroups(token) async {
    final http.Response? response = await http.get(
        Uri.parse('https://hello-cycu-delivery-service.herokuapp.com/group/'),
        headers: {
          "token": '$token',
          "Content-Type": "application/x-www-form-urlencoded",
          "id": '62bfabae55036d765d2adfbf',
        });

    if (response!.statusCode == 200) {
      var obj = Autogenerated.fromJson(jsonDecode(response.body));
      var myaddress = (obj.result as List<Result2?>);
      print('the response body of groupApi in Form3 $myaddress');
      debugPrint('status200 of groupApi in Form3');
      return myaddress;
    } else if (response.statusCode == 403) {
      debugPrint('status403 of groupApi in Form3');
      return null;
    } else {
      throw Exception('Failed to load store');
    }
  }
}
