class Autogenerated {
  String? status;
  bool? code;
  List<Result2>? result;

  Autogenerated({this.status, this.code, this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    if (json['result'] != null) {
      result = <Result2>[];
      json['result'].forEach((v) {
        result!.add(new Result2.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    if (this.result != null) {
      data['result'] = this.result!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Result2 {
  String? name;
  String? address;
  String? url;
  String? image;

  Result2({this.name, this.address, this.url,this.image});

  Result2.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    address = json['address'];
    url = json['url'];
    image = json['image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['address'] = this.address;
    data['url'] = this.url;
    data['image']= this.image;
    return data;
  }
}
