class MenuAutogenerated {
  String? status;
  bool? code;
  Result3? result;

  MenuAutogenerated({this.status, this.code, this.result});

  MenuAutogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    result =
        json['result'] != null ? new Result3.fromJson(json['result']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    if (this.result != null) {
      data['result'] = this.result!.toJson();
    }
    return data;
  }
}

class Result3 {
  String? name;
  String? address;
  String? url;
  String? image;
  String? timeEstimate;
  List<bool>? businessTime;
  String? place;
  String? describe;
  List<Result>? product;
  String? discount;

  Result3({
    this.name,
    this.address,
    this.url,
    this.timeEstimate,
    this.businessTime,
    this.place,
    this.describe,
    this.product,
    this.image,
    this.discount,
  });

  Result3.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    address = json['address'];
    url = json['url'];
    timeEstimate = json['timeEstimate'];
    if (json['businessTime'] != null) {
      businessTime = [];
      for (var v in (json['businessTime'] as List)) {
        businessTime!.add(v);
      }
    }
    place = json['place'];
    describe = json['describe'];
    if (json['product'] != null) {
      product = <Result>[];
      for (var v in (json['product'] as List)) {
        product!.add(Result.fromJson(v));
      }
    }
    image = json['image'];
    discount = json['discount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['address'] = this.address;
    data['url'] = this.url;
    data['timeEstimate'] = this.timeEstimate;
    data['businessTime'] = this.businessTime;
    data['place'] = this.place;
    data['describe'] = this.describe;
    data['product'] = this.product;
    data['image'] = this.image;
    data['discount'] = this.discount;
    return data;
  }
}

class Result {
  late String name;
  late String price;
  String? describe;
  late String type;
  String? discount;
  String? min;
  String? max;
  String? options;
  String? image;
  String? id;

  Result({
    required this.name,
    required this.price,
    required this.describe,
    required this.type,
    required this.image,
    required this.discount,
    required this.options,
    required this.id,
    required this.max,
    required this.min,
  });

  Result.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    price = json['price'];
    describe = json['describe'];
    type = json['type'];
    image = json['image'];
    discount = json['discount'];
    options = json['options'];
    id = json['id'];
    max = json['max'];
    min = json['min'];
  }
}
