import 'package:flutter/widgets.dart';
import 'package:flutterdemo02/API/shopCarModel.dart';
import 'package:get/get.dart';

import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:async';

import '../controllers/cart_controller.dart';

class shopCarApi {
  shopCarApi({required this.token});
  String token;
  static Future getCar(key) async {
    final CartController cartController = Get.find();
    print(
        'this is cartController.options() in shopCarApi ${cartController.options()}');
    var response = await http.post(
      Uri.parse("https://www.foodone.tw/member/user/order"),
      headers: {
        "token": key,
        "Content-Type": "application/json",
      },
      body: cartController.options(),
    );
    // print("this is response ${response}");
    // print("this is response ${response.body}");

    // print("this is response headers ${response.headers}");
    // print("this is refresh_token ${response.headers['refresh_token']}");
    debugPrint('the statuscode in shopCarApi is ${response.statusCode}');
    debugPrint('the body in shopCarApi is ${response.body}');
    if (response.statusCode == 201) {
      var obj = Autogenerated.fromJson(jsonDecode(response.body));
      debugPrint('statuscode is ${response.statusCode}');
      return obj;
    } else if (response.statusCode == 403) {
      debugPrint('statuscode is ${response.statusCode}');
      return null;
    } else {
       var obj = jsonDecode(response.body);
      return obj['code'];
    }
  }
}
