// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdDky0dxSPZU_iJAa0z1DY9F-aQ40JOPM',
    appId: '1:827645634937:android:80c437b04ffaa942d3a7a8',
    messagingSenderId: '827645634937',
    projectId: 'absolute-text-353909',
    storageBucket: 'absolute-text-353909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ifnI9b_0hZfoqGPvGUikJdtD8YdIlmE',
    appId: '1:827645634937:ios:72d2360cf093b71cd3a7a8',
    messagingSenderId: '827645634937',
    projectId: 'absolute-text-353909',
    storageBucket: 'absolute-text-353909.appspot.com',
    androidClientId: '827645634937-je0h9ii2gvknm8cc7lrc5q7qghsdr40q.apps.googleusercontent.com',
    iosClientId: '827645634937-g6q4ufgdtn0d471eg47qb92ifi8o6fc3.apps.googleusercontent.com',
    iosBundleId: 'com.FORDON.flutterdemo02',
  );
}
